service:
  name: jumpstart
  awsKmsKeyArn: arn:aws:kms:us-east-1:704903784842:key/eacaee39-1f83-469c-9d1a-29a8d452bb09

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: ssm:GetParameters
      Resource:
        'Fn::Join':
          - ':'
          - - 'arn:aws:ssm'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - parameter/${self:custom.service.name}/${self:custom.stage}/*
  environment:
    STAGE: ${self:custom.stage}
    SERVICE_NAME: ${self:custom.service.name}
custom:
  stage: ${opt:stage, self:provider.stage} # shortcut for current stage
  service: ${file(serverless.yml):service} # workaround for ${self:service}
functions:
  jumpstart:
    handler: handler.jumpstart
    events:
      - schedule: 'cron(0 12 ? * MON-FRI *)'
